name:                 etna-workload
version:              0.0.0
visibility:           public
id:                   etna-workload-0.0.0-1Angt82Ho29C3S4rUACHko
key:                  etna-workload-0.0.0-1Angt82Ho29C3S4rUACHko
abi:                  c1694f30cd1654221c42ec034d18d785
exposed:              True
exposed-modules:
    Impl Spec Strategy.Correct Strategy.Lean Strategy.LeanRev
    Strategy.Quick Strategy.QuickIndex Strategy.Small Strategy.SmallRev
    Type Util

hidden-modules:       Paths_etna_workload
import-dirs:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/lib/aarch64-osx-ghc-9.0.2/etna-workload-0.0.0-1Angt82Ho29C3S4rUACHko

library-dirs:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/lib/aarch64-osx-ghc-9.0.2/etna-workload-0.0.0-1Angt82Ho29C3S4rUACHko

dynamic-library-dirs:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/lib/aarch64-osx-ghc-9.0.2

data-dir:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/share/aarch64-osx-ghc-9.0.2/etna-workload-0.0.0

hs-libraries:         HSetna-workload-0.0.0-1Angt82Ho29C3S4rUACHko
include-dirs:
    /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/ffi

depends:
    QuickCheck-2.14.2-ES2KdaVhPj0ArXGpBBlTr8 base-4.15.1.0
    etna-lib-0.1.0.0-8ewiBVQOHgX3MSlsAXNfqt
    generic-random-1.5.0.1-Fpm39eb6S4LDckX57pmGE0
    leancheck-0.9.10-85gqWNPLTz0BWM88m44GNp
    smallcheck-1.2.1-BwqIzlGIaGNGxc4nvHJ9hQ

haddock-interfaces:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/doc/etna-workload-0.0.0/etna-workload.haddock

haddock-html:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/doc/etna-workload-0.0.0
