name:                 etna-lib
version:              0.1.0.0
visibility:           public
id:                   etna-lib-0.1.0.0-8ewiBVQOHgX3MSlsAXNfqt
key:                  etna-lib-0.1.0.0-8ewiBVQOHgX3MSlsAXNfqt
abi:                  8e437802f4e412f20da377bd3073f4b7
exposed:              True
exposed-modules:
    Etna.Lib Etna.Lib.Strategy.LeanCheck Etna.Lib.Strategy.QuickCheck
    Etna.Lib.Strategy.SmallCheck Etna.Lib.TH Etna.Lib.Trial
    Etna.Lib.Types Etna.Lib.Util

hidden-modules:       Paths_etna_lib
import-dirs:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/lib/aarch64-osx-ghc-9.0.2/etna-lib-0.1.0.0-8ewiBVQOHgX3MSlsAXNfqt

library-dirs:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/lib/aarch64-osx-ghc-9.0.2/etna-lib-0.1.0.0-8ewiBVQOHgX3MSlsAXNfqt

dynamic-library-dirs:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/lib/aarch64-osx-ghc-9.0.2

data-dir:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/share/aarch64-osx-ghc-9.0.2/etna-lib-0.1.0.0

hs-libraries:         HSetna-lib-0.1.0.0-8ewiBVQOHgX3MSlsAXNfqt
include-dirs:
    /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/ffi

depends:
    QuickCheck-2.14.2-ES2KdaVhPj0ArXGpBBlTr8
    aeson-2.0.3.0-4gvvzfqcJFlInzrfkNClfo base-4.15.1.0
    bytestring-0.10.12.1 clock-0.8.3-GzO0xcEybVZ5lfbzIigoQK
    leancheck-0.9.10-85gqWNPLTz0BWM88m44GNp
    regex-tdfa-1.3.1.2-Bln9X5VZunR99Vule6qtbf
    silently-1.2.5.2-KvFvN8XiRhqBA56Sfh5QQ1
    smallcheck-1.2.1-BwqIzlGIaGNGxc4nvHJ9hQ template-haskell-2.17.0.0
    timeit-2.0-13BYXbUXu2MJzbvDZuPEww

haddock-interfaces:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/doc/etna-lib-0.1.0.0/etna-lib.haddock

haddock-html:
    /Users/akeles/Programming/projects/PbtBenchmark/etna/workloads/Haskell/FSUB/.stack-work/install/aarch64-osx/4f0a2e23ab5ced38d0c59d030489910952f1412068c84340cda7b286690ea7f0/9.0.2/doc/etna-lib-0.1.0.0
