lib: [
  "_build/install/default/lib/util/.private/util__Parse.cmi" {".private/util__Parse.cmi"}
  "_build/install/default/lib/util/.private/util__Parse.cmt" {".private/util__Parse.cmt"}
  "_build/install/default/lib/util/META"
  "_build/install/default/lib/util/core_plus.ml"
  "_build/install/default/lib/util/dune-package"
  "_build/install/default/lib/util/io.ml"
  "_build/install/default/lib/util/io.mli"
  "_build/install/default/lib/util/opam"
  "_build/install/default/lib/util/parse.ml"
  "_build/install/default/lib/util/runner.ml"
  "_build/install/default/lib/util/util.a"
  "_build/install/default/lib/util/util.cma"
  "_build/install/default/lib/util/util.cmi"
  "_build/install/default/lib/util/util.cmt"
  "_build/install/default/lib/util/util.cmx"
  "_build/install/default/lib/util/util.cmxa"
  "_build/install/default/lib/util/util.ml"
  "_build/install/default/lib/util/util__Core_plus.cmi"
  "_build/install/default/lib/util/util__Core_plus.cmt"
  "_build/install/default/lib/util/util__Core_plus.cmx"
  "_build/install/default/lib/util/util__Io.cmi"
  "_build/install/default/lib/util/util__Io.cmt"
  "_build/install/default/lib/util/util__Io.cmti"
  "_build/install/default/lib/util/util__Io.cmx"
  "_build/install/default/lib/util/util__Parse.cmx"
  "_build/install/default/lib/util/util__Runner.cmi"
  "_build/install/default/lib/util/util__Runner.cmt"
  "_build/install/default/lib/util/util__Runner.cmx"
]
libexec: [
  "_build/install/default/lib/util/util.cmxs"
]
bin: [
  "_build/install/default/bin/util"
]
